console.log(`NOTES: PINDAH REST API NGABB`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)
console.log(`https://danzzapi.xyz`)